---
- hosts: ESXiHosts[0]
  tasks:
  - name: Gather cluster facts from given datacenter
    vmware_cluster_facts:
      hostname: "{{ vmvcenter }}"
      username: "{{ VCC_USERNAME }}"
      password: "{{ VCC_PASSWORD }}"
      datacenter: "{{ vmdatacenter }}"
      validate_certs: no
    delegate_to: localhost
    register: cluster_facts
