---
- hosts: ESXiHosts[0]
  connection: local
  tasks:
  - name: Gather cluster facts from given datacenter
    vmware_cluster_facts:
      hostname: "{{ vmvcenter }}"
      username: "{{ VCC_USERNAME }}"
      password: "{{ VCC_PASSWORD }}"
      datacenter: "{{ vmdatacenter }}"
      validate_certs: false
    register: cluster_facts_json

  - name: Debug Info
    debug:
      var: item
    loop: "{{cluster_facts_json.clusters}}"
  
  - name: Gather cluster facts from given datacenter
    vmware_resource_pool_facts:
      hostname: "{{ vmvcenter }}"
      username: "{{ VCC_USERNAME }}"
      password: "{{ VCC_PASSWORD }}"
      validate_certs: false
    register: rp_facts
