---
- hosts: ESXiHosts[0]
  vars:
    wantedcluster: CLUSTER01
  connection: local
  tasks:
  - name: Grab cluster facts
    vmware_cluster_facts:
      hostname: "{{ vmvcenter }}"
      username: "{{ VCC_USERNAME }}"
      password: "{{ VCC_PASSWORD }}"
      datacenter: "{{ vmdatacenter }}"
      validate_certs: false
    register: cluster_facts_json
  
  - name: Loop with with_dict
    with_dict: "{{ cluster_facts_json['clusters'] }}"
    when: item.key == wantedcluster
    ignore_errors: yes
  
  - name: Grab resource pool facts
    vmware_resource_pool_facts:
      hostname: "{{ vmvcenter }}"
      username: "{{ VCC_USERNAME }}"
      password: "{{ VCC_PASSWORD }}"
      validate_certs: false
    register: rp_facts
  
  - debug: var=rp_facts.resource_pool_facts
    
  - name: Loop with loop
    debug: msg={{ item.runtime_cpu_max_usage }}
    loop: "{{ rp_facts.resource_pool_facts }}"
    loop_control:
      label: "{{ item.runtime_cpu_max_usage }}"
    ignore_errors: yes

