---
- hosts: ESXiHosts[0]
  connection: local
  tasks:
  - name: Grab cluster facts
    vmware_cluster_facts:
      hostname: "{{ vmvcenter }}"
      username: "{{ VCC_USERNAME }}"
      password: "{{ VCC_PASSWORD }}"
      datacenter: "{{ vmdatacenter }}"
      validate_certs: false
    register: cluster_facts_json

  - debug: var=cluster_facts_json.clusters
  
  - name: Loop with with_dict
    with_dict: "{{ cluster_facts_json['clusters'] }}"
    debug: msg="{{ item.key }}"


  
  - name: Grab resource pool facts
    vmware_resource_pool_facts:
      hostname: "{{ vmvcenter }}"
      username: "{{ VCC_USERNAME }}"
      password: "{{ VCC_PASSWORD }}"
      validate_certs: false
    register: rp_facts
  
  - debug: var=rp_facts 
    
  - name: Loop with loop
    loop: "{{ rp_facts }}"
    debug: msg="{{ item.owner }}"
