---
- hosts: ESXiHosts[0]
  gather_facts: no
  vars:
    wantedcluster: CLUSTER01
    usedmemory: 0
  connection: local
  tasks:
  - name: Grab cluster facts
    vmware_cluster_info:
      hostname: "{{ vmvcenter }}"
      username: "{{ VCC_USERNAME }}"
      password: "{{ VCC_PASSWORD }}"
      datacenter: "{{ vmdatacenter }}"
      validate_certs: false
    register: cluster_facts_json
  
  - debug: var=cluster_facts_json
  
  - name: Loop with with_dict
    set_fact: 
      drsstatus: "{{ item.value.enabled_drs }}"
      hastatus: "{{ item.value.enable_ha }}"
    with_dict: "{{ cluster_facts_json['clusters'] }}"
    when: item.key == wantedcluster
    loop_control:
      label: "{{ item }}"
    ignore_errors: yes
  
  - name: Grab resource pool facts
    vmware_resource_pool_info_custom:
      hostname: "{{ vmvcenter }}"
      username: "{{ VCC_USERNAME }}"
      password: "{{ VCC_PASSWORD }}"
      validate_certs: false
    register: rp_facts

  - name: Loop with loop
    set_fact: 
      cpuusage: "{{ item.runtime_cpu_max_usage }}"
      memusage: "{{item.runtime_memory_overall_usage }}"
    loop: "{{ rp_facts.resource_pool_info }}"
    when: item.owner == wantedcluster
    loop_control:
      label: "{{ item.runtime_cpu_max_usage }}"
    ignore_errors: yes

  - debug: var=wantedcluster
  - debug: var=drsstatus
  - debug: var=hastatus  
  - debug: var=cpuusage
  - debug: var=memusage
