---
- hosts: Hosts
  connection: local
  tasks:
  - name: Collect facts
    vmware_cluster_facts:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      cluster_name: "{{ inventory_hostname }}"
      validate_certs: false
    register: cluster_facts
    
  - name: Create Datastore
    vmware_host_datastore:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ inventory_hostname }}"
      datastore_name: "{{ datastore_name }}"
      datastore_type: "{{ datastore_type }}"
      vmfs_device_name: "{{ deviceID }}"
      vmfs_version: 6
      state: present
      validate_certs: false      
      
