---
- hosts: ESXiHosts[0]
  connection: local
  tasks:
  - name: Create Datastore
    vmware_host_datastore:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ VCC_username }}"
      password: "{{ VCC_password }}"
      esxi_hostname: "{{ inventory_hostname }}"
      datastore_name: "{{ datastore_name }}"
      datastore_type: "{{ datastore_type }}"
      vmfs_device_name: "{{ deviceID }}"
      vmfs_version: 6
      state: present
      validate_certs: false      
      
