---
- hosts: ESXiHosts[0]
  gather_facts: no
  connection: local
  vars:
  tasks:
  - name: Deploy from template
    vmware_guest :
      hostname: 192.168.1.10
      username: "{{ VCC_USERNAME }}"
      password: "{{ VCC_PASSWORD }}"
      name: "{{ vmname }}"
      guest_id: centos64Guest
      folder: /Lancaster/vm/
      template: centostemplate
      cluster: "{{ vmcluster }}"
      disk:
      - size_gb: "{{ vmdisksize }}"
        type: thin
        datastore: "{{ vmdatastore }}"
      hardware:
        memory_mb: "{{ vmmemory }}"
        num_cpus: "{{ vmcpu }}"
        scsi: paravirtual
      wait_for_ip_address: yes
      state: poweredon
      validate_certs: false
