---
- hosts: ESXiHosts[0]
  connection: local
  vars:
  tasks:
  - name: Dismount NFS Datastore
    vmware_host_powerstate :
      esxi_hostname: "{{ esxi_hostname }}"
      hostname: "{{ esxi_hostname }}"
      username: "{{ ESXi_USERNAME }}"
      password: "{{ ESXi_PASSWORD }}"
      state: shutdown-host
      force: true
      validate_certs: false           
