---
- hosts: ESXiHosts[0]
  gather_facts: no
  connection: local
  vars:
  tasks:
  - name: update servicenow request
    snow_record:
      username: "{{ snow_user }}"
      password: "{{ snow_password }}"
      instance: "{{ snow_instance }}"
      state: present
      table: sc_request
      number: "{{ snow_request }}"
      data:
        work_notes: "Sample CPU number"
    ignore_errors: yes
