---
- hosts: VMs
  gather_facts: no
  connection: local
  vars:
  tasks:
  - name: update servicenow request
    snow_record:
      username: "{{ snow_user }}"
      password: "{{ snow_password }}"
      instance: "{{ snow_instance }}"
      state: present
      table: sc_req_item
      number: "RITM{{ snow_request.split('REQ')[1] }}"
      data:
        work_notes: "Started ansible playbook"
  - name: Start VMs
    vmware_guest_powerstate :
      hostname: "{{ esxi_hostname}}"
      username: "{{ ESXi_USERNAME }}"
      password: "{{ ESXi_PASSWORD }}"
      name: "{{ inventory_hostname }}"
      state: powered-on
      validate_certs: false
  - pause:
      minutes: 3
  - name: update servicenow request
    snow_record:
      username: "{{ snow_user }}"
      password: "{{ snow_password }}"
      instance: "{{ snow_instance }}"
      state: present
      table: sc_req_item
      number: "RITM{{ snow_request.split('REQ')[1] }}"
      data:
        work_notes: "Started core VM {{ inventory_hostname }}"
      
- hosts: ESXiHosts
  gather_facts: no
  connection: local
  vars:
  tasks:
  - name: Exit Maintenance Mode
    vmware_maintenancemode:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ VCC_USERNAME }}"
      password: "{{ VCC_PASSWORD }}"
      esxi_hostname: "{{ inventory_hostname }}"
      evacuate: yes
      timeout: 3600
      state: absent
      validate_certs: false
  - name: update servicenow request
    snow_record:
      username: "{{ snow_user }}"
      password: "{{ snow_password }}"
      instance: "{{ snow_instance }}"
      state: present
      table: sc_req_item
      number: "RITM{{ snow_request.split('REQ')[1] }}"
      data:
        work_notes: "{{ inventory_hostname }} taken out of maintenance mode"
        
- hosts: NestedVMs
  gather_facts: no
  connection: local
  vars:
  tasks:
  - name: Start Nested VMs
    vmware_guest_powerstate :
      hostname: "{{ vcenter_hostname }}"
      username: "{{ VCC_USERNAME }}"
      password: "{{ VCC_PASSWORD }}"
      name: "{{ inventory_hostname }}"
      state: powered-on
      validate_certs: false
  - name: update and close servicenow request
    snow_record:
      username: "{{ snow_user }}"
      password: "{{ snow_password }}"
      instance: "{{ snow_instance }}"
      state: present
      table: sc_req_item
      number: "RITM{{ snow_request.split('REQ')[1] }}"
      data:
        work_notes: "Started nested VM {{ inventory_hostname }}"
        state: 3
