---
- hosts: ESXiHosts[0]
  gather_facts: no
  connection: local
  vars:
  tasks:
  - name: update servicenow request
    snow_record:
      username: "{{ snow_user }}"
      password: "{{ snow_password }}"
      instance: "{{ snow_instance }}"
      state: present
      table: u_chrisrequest
      number: "{{ snow_request }}"
      data:
        work_notes: "Prechecks run"
        u_available_cpu: "Lots CPU"
        u_available_mem: "Lots MEM"
    ignore_errors: yes
