---
- hosts: VMs
  connection: local
  vars:
    vcenter_hostname: 192.168.2.5
    vcenter_username: root
    vcenter_password: TiffanyDenman2010
    esxi_hostname: 192.168.2.11
  
  tasks:
  - name: Start VMs
    vmware_guest_powerstate :
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      name: "{{ inventory_hostname }}"
      state: powered-on
      validate_certs: false
  - pause:
    minutes: 5
      
- hosts: Hosts
  connection: local
  vars:
    vcenter_hostname: 192.168.2.10
    vcenter_username: administrator@vsphere.local
    vcenter_password: TiffanyDenman2010!
    esxi_hostname: 192.168.2.11
    
  tasks:
  - name: Exit Maintenance Mode
    vmware_maintenancemode:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ inventory_hostname }}"
      evacuate: yes
      timeout: 3600
      state: absent
      validate_certs: false
      
- hosts: NestedVMs
  connection: local
  vars:
    vcenter_hostname: 192.168.2.10
    vcenter_username: administrator@vsphere.local
    vcenter_password: TiffanyDenman2010!
    esxi_hostname: 192.168.2.11
  
  tasks:
  - name: Start Nested VMs
    vmware_guest_powerstate :
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      name: "{{ inventory_hostname }}"
      state: powered-on
      validate_certs: false
  


