---
- hosts: NestedVMs
  connection: local
  vars:
  tasks:
  - name: Shutdown Nested VMs
    vmware_guest_powerstate :
      hostname: "{{ vcenter_hostname }}"
      username: "{{ VCC_USERNAME}}"
      password: "{{ VCC_PASSWORD }}"
      name: "{{ inventory_hostname }}"
      state: powered-off
      validate_certs: false
  
- hosts: Hosts
  connection: local
  vars:
  tasks:
  - name: Enter Maintenance Mode
    vmware_maintenancemode:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ VCC_USERNAME }}"
      password: "{{ VCC_PASSWORD }}"
      esxi_hostname: "{{ inventory_hostname }}"
      evacuate: yes
      timeout: 3600
      state: present
      validate_certs: false

- hosts: VMs
  connection: local
  vars:
  tasks:
  - name: Shutdown Nested VMs
    vmware_guest_powerstate :
      hostname: "{{ esxi_hostname }}"
      username: "{{ ESXi_USERNAME }}"
      password: "{{ ESXi_PASSWORD}}"
      name: "{{ inventory_hostname }}"
      state: shutdown-guest
      validate_certs: false
