---
- hosts: VMs
  connection: local
  vars:
    vcenter_hostname: 192.168.2.10
    vcenter_username: administrator@vsphere.local
    vcenter_password: TiffanyDenman2010!
    esxi_hostname: 192.168.2.11
  
  tasks:
    - name: Shutdown VMs
    vmware_guest_powerstate :
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ esxi_hostname }}"
      name: "TinyVM01"
      state: powered-off
      validate_certs: false
  
- hosts: hosts
  connection: local
  vars:
    vcenter_hostname: 192.168.2.10
    vcenter_username: administrator@vsphere.local
    vcenter_password: TiffanyDenman2010!
    esxi_hostname: 192.168.2.11
    
  tasks:
    - name: Enter Maintenance Mode
    vmware_maintenancemode:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ esxi_hostname }}"
      evacuate: yes
      timeout: 3600
      state: present
      validate_certs: false
