---
- hosts: ESXiHosts[0]
  connection: local
  vars:
  tasks:
  - name: Dismount NFS Datastore
    vmware_host_datastore :
      hostname: "{{ esxi_hostname }}"
      username: "{{ ESXi_USERNAME }}"
      password: "{{ ESXi_PASSWORD }}"
      datastore_name: NFS01
      datastore_type: NFS
      state: absent
      validate_certs: false      
